spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ithurts?serverTimezone=UTC&characterEncoding=UTF-8"
    username: root
    password: SideProject1!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop # Constraint Drop Error
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  profiles:
    include: API-KEY

logging:
  level:
    org.hibernate.sql: trace
    org.hibernate.type: trace
    root: info
    com.sidepj.ithurts: trace


