spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ithurts?serverTimezone=UTC&characterEncoding=UTF-8"
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL5SpatialDialect
  profiles:
    include: API-KEY
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: info
    root: info
    com.sidepj.ithurts: trace


